version: '3.8'
services:
  sdb-core:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: ./sdb-main
    ports:
      - "8080:8080"

  sdb-logging:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: ./sdb-logging
    ports:
      - "8082:8082"