version: '3.8'
services:
  sdb-rabbit:
    image: rabbitmq:3.13.7-management
    hostname: sdb-rabbit
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=sdb_admin
      - RABBITMQ_DEFAULT_PASS=sdb_password
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  common-utils:
    build:
      context: .
      dockerfile: ./common-utils/Dockerfile
    image: common-utils:latest

  sdb-core:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: 
      context: .
      dockerfile: ./sdb-main/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sdb-rabbit
      - common-utils

  sdb-warehouse:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build:
      context: .
      dockerfile: ./sdb-warehouse/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - sdb-rabbit
      - common-utils

  sdb-logging:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build:
      context: .
      dockerfile: ./sdb-logging/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - sdb-rabbit
      - common-utils

volumes:
  rabbitmq_data: