server:
  port: 8080
  address: localhost

spring:
  application:
    name: sdb-core
  profiles:
    active: default
  hikari:
    connection-timeout: 20000
    minimum-idle: 10
    maximum-pool-size: 30
    idle-timeout: 10000
    max-lifetime: 1000
    auto-commit: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: public
    locations: classpath:db/migration/core
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

security:
  admin:
    usernames:
      - yustalius
---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5432/sdb_core"
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: "sdb_admin"
    password: "sdb_password"

server:
  port: 8080
  address: localhost

app:
  database:
    url: "jdbc:postgresql://127.0.0.1:5432/sdb_core"
    username: "postgres"
    password: 1234
  logging:
    url: "http://localhost:8082/"

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: "jdbc:postgresql://host.docker.internal:5432/sdb_core"
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: host.docker.internal
    port: 5672
    username: "sdb_admin"
    password: "sdb_password"

server:
  port: 8080
  address: 0.0.0.0

app:
  database:
    url: "jdbc:postgresql://host.docker.internal:5432/sdb_core"
    username: "postgres"
    password: 1234
  logging:
    url: "http://host.docker.internal:8082/"